language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-testify' ]; then cd .. && eval "mv $currentfolder generator-testify" && cd generator-testify; fi

